apiVersion: v1
kind: Service
metadata:
  name: pokeapi
  labels:
    component: pokeapi
  annotations:
    ingress.kubernetes.io/balance-algorithm: leastconn
spec:
  selector:
    component: pokeapi
  ports:
    - port: 80
      targetPort: 8080
