apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume0
  labels:
    type: local
    component: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:  # TODO: change to a cloud-solution
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim0
  labels:
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
