apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-volume0
  labels:
    type: local
    component: redis
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:  # TODO: change to a cloud-solution
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-claim0
  labels:
    component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
